### ISSUE TITLE
bug report - Dail status panel is missing

### ISSUE THREAD

**Issue by wangsd01** [mdmower/android_kernel_huawei_msm8928#1]
After I dial the number and call out. The dial status panel doesn't show up, which means I can't hang up...  
version: lineage-14.1-20171124-UNOFFICIAL-mt2.zip	(309 MB) 
Huawei Mate2

**Comment by mdmower** [comment]
Unable to reproduce. Did you notice the dialpad button that brings up the dialpad after a call has connected? I also see a red 'end call' button as soon as a call connects. Perhaps you can provide a screencast?

This issue does not belong in kernel issues. Please use [android.cmphys.com/grievances-and-other-words](https://android.cmphys.com/grievances-and-other-words/) instead.

**Comment by wangsd01** [comment]
Thank you! I solve this problem by using the old recovery twrp-3.1.N0-0-mt2.img instead of the new twrp-3.1.N1-0-mt2.img
